import java.io.IOException;

public class Chapter15_4 {
	public static void main(String[] args) throws IOException {
		throw new IOException("IOException例外が発生しました。");
	}
}
